name: CI_CD_practice_project_04_02
on: 
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - dev
  workflow_dispatch:
  push:
    paths:
      - '/practice_project_04_02/src/components/**.jsx'
    branches:
      - main
      - dev
      - 'dev-*' # dev-new, dev-this-is-new
      - 'feat/**' # feat/dev/new

# Just comment to test skip process of CI 


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd practice_project_04_02
          npm ci
      - name: Test code
        run: | 
          cd practice_project_04_02
          npm run test
      - name: Build code
        run: | 
            cd practice_project_04_02  
            npm run build
      - name: Deploy project
        run: echo "Deploying........."