name: CI_CD_practice_project_04_02
on: 
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - dev
  workflow_dispatch:
  push:
    paths:
      - '/practice_project_04_02/src/components/**.jsx'
    branches:
      - main
      - dev
      - 'dev-*' # dev-new, dev-this-is-new
      - 'feat/**' # feat/dev/new

# Just comment to test skip process of CI 


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd practice_project_04_02
          npm ci
      - name: Test code
        run: |
          cd practice_project_04_02
          npm run test

  Build_Artifact:
    needs: [CI]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install denepndencies
        run: |
          cd practice_project_04_02
          npm ci
      - name: Build code
        run: |
            cd practice_project_04_02  
            npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: |
            practice_project_04_02/dist
            practice_project_04_02/package.json

  Deploy:
      needs: [CI, Build_Artifact]
      if: success()
      runs-on: ubuntu-latest
      steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-file
      - name: Output contents
        run: |
          ls
      - name: Deploy project
        run: echo "Deploying........."